# Healing Plugin Configuration
plugin.healing.sleep-time=15
plugin.healing.blocked-coefficient=2
plugin.healing.max-replicas=2
# percentage of change, 10 meaning change bigger than 10%
plugin.healing.stats.change-percentage=10
# percentage of job error that triggers the killing of all jobs (stop condition)
plugin.healing.stats.max-error-job-percentage=60
# percentage of invocations partial error that triggers the killing of all jobs (stop condition)
plugin.healing.stats.max-error-invocation-percentage=99.9
# minimum number of invocations per workflow in STOP condition
plugin.healing.min-invocations=100